# Generated by Django 4.2 on 2023-06-04 14:31

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('graduated', 'Graduated'), ('not graduated', 'Not Graduated')], default='active', max_length=20)),
                ('surname', models.CharField(default=None, max_length=200)),
                ('othernames', models.CharField(default=None, max_length=200)),
                ('regNo', models.CharField(max_length=200, unique=True)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('program_level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma')], default='certificate', max_length=30)),
                ('program', models.CharField(choices=[('ndict', 'NDICT'), ('ndbce', 'NDBCE')], default='ndict', max_length=50)),
                ('center', models.CharField(choices=[('mbi', 'MBI'), ('mubs', 'MUBS')], default='mbi', max_length=50)),
                ('start_year', models.DateField(default=django.utils.timezone.now)),
                ('finish_year', models.DateField(default=django.utils.timezone.now)),
                ('transcript_status', models.CharField(choices=[('recieved', 'Recieved'), ('not recieved', 'Not Recieved')], default='recieved', max_length=30)),
                ('certificate_status', models.CharField(choices=[('recieved', 'Recieved'), ('not recieved', 'Not Recieved')], default='received', max_length=30)),
                ('employment_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10)),
                ('employment_entity', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='government', max_length=20)),
            ],
            options={
                'ordering': ['regNo'],
            },
        ),
    ]
