# Generated by Django 4.2.1 on 2023-06-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubiteb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='employment_entity',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('ngo', 'NGO'), ('missionnary', 'Missionary')], default='government', max_length=20),
        ),
    ]
