# Generated by Django 4.2 on 2023-06-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubiteb', '0003_alumni_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='phone_number',
        ),
    ]
