# Generated by Django 4.2 on 2023-06-05 00:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ubiteb', '0005_alumni_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
