# Generated by Django 4.2 on 2023-06-06 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0006_alter_alumni_phone_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="alumni", name="finish_year",),
        migrations.AddField(
            model_name="alumni",
            name="completion_year",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="start_year",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
