# Generated by Django 4.2 on 2023-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0009_alter_alumni_completion_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="certificate_status",
            field=models.CharField(
                choices=[("recieved", "Received"), ("not received", "Not Received")],
                default="received",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="employment_status",
            field=models.CharField(
                choices=[("employed", "Employed"), ("unemployed", "Unemployed")],
                default="employed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="transcript_status",
            field=models.CharField(
                choices=[("received", "Received"), ("not received", "Not Received")],
                default="received",
                max_length=30,
            ),
        ),
    ]
