# Generated by Django 4.2 on 2023-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0011_alter_alumni_certificate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="employment_entity",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("private", "Private"),
                    ("ngo", "NGO"),
                    ("missionnary", "Missionary"),
                    ("none", "None"),
                ],
                default="government",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="employment_status",
            field=models.CharField(
                choices=[("employed", "Employed"), ("unemployed", "Unemployed")],
                default="employed",
                max_length=40,
            ),
        ),
    ]
