# Generated by Django 4.2.1 on 2023-06-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubiteb', '0014_alumnibulkupload_alter_alumni_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniBulkUpload',
        ),
    ]
