# Generated by Django 4.2 on 2023-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0017_alter_alumni_program_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="employment_entity",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("private", "Private"),
                    ("ngo", "NGO"),
                    ("missionary", "Missionary"),
                    ("none", "None"),
                ],
                default="government",
                max_length=40,
            ),
        ),
    ]
