# Generated by Django 4.2 on 2023-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0018_alter_alumni_employment_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="program_level",
            field=models.CharField(
                choices=[
                    ("higher diploma", "Higher Diploma"),
                    ("diploma", "Diploma"),
                    ("national certificate", "National Certificate"),
                    ("ucpc", "Uganda Community of Polytechnic Certificate"),
                ],
                default="Certificate",
                max_length=30,
            ),
        ),
    ]
