# Generated by Django 4.2 on 2023-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0021_remove_alumni_center_alumni_exam_center_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="exam_center",
            field=models.CharField(choices=[], default="None", max_length=200),
        ),
    ]
