# Generated by Django 4.2 on 2023-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0022_alter_alumni_exam_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="exam_center",
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
