# Generated by Django 4.2 on 2023-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0024_alter_alumni_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="program",
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
