# Generated by Django 4.2 on 2023-06-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ubiteb", "0025_alter_alumni_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumni",
            name="district",
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
